export RTOS_SDK_PATH=${HOME}/ti-processor-sdk-rtos-j721e-evm-09_00_01_01
export MCUSW_SDK_PATH=${RTOS_SDK_PATH}/mcusw
export PDK_SDK_PATH=${RTOS_SDK_PATH}/pdk_jacinto_09_00_01_04
export TIARMCLANG_CC_FLAG=-g -DMAKEFILE_BUILD -c -Wall -Werror -Wno-extra -Wno-exceptions -ferror-limit=100 -Wno-unused-command-line-argument -Wno-gnu-variable-sized-type-not-at-end -Wno-unused-function -Wno-extern-initializer -Wno-excess-initializers -Wno-bitfield-constant-conversion -Wno-address-of-packed-member -EL -eo.oer5f -ea.ser5f -g -mfloat-abi=hard -mfpu=vfpv3-d16 -mcpu=cortex-r5 -march=armv7-r -Werror -Oz -s -DBUILD_MCU1_0 -DBUILD_MCU -DAUTOSAR_431 -DUART_ENABLED -DSOC_J721E -Dj721e_evm=j721e_evm
export TIARMCLANG_LD_FLAG=-Werror -Xlinker -q -Xlinker -u -Xlinker _c_int00 -Xlinker --display_error_number -Xlinker --use_memcpy=fast -Xlinker --use_memset=fast -Xlinker --diag_suppress=10063-D  -Xlinker --diag_suppress=10068-D -Xlinker --diag_suppress=10083-D -Xlinker -c -mcpu=cortex-r5 -march=armv7-r -Xlinker -x -Xlinker --zero_init=on -Xlinker -x -Xlinker --zero_init=on -Xlinker --define=BUILD_MCU1_0 -Xlinker --define=BUILD_MCU  -Xlinker --diag_suppress=10068
export WDG_INCLUDE_PATH=-I. -Isoc/j721e/mcu1_0 -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/IntRtr_Cfg/soc/j721e/mcu1_0/ -I${MCUSW_SDK_PATH}/mcal_drv/mcal -I${PDK_SDK_PATH}/packages -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Mcu_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Adc_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Can_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Dio_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Eth_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/EthTrcv_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Gpt_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Spi_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Wdg_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Pwm_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/CddIpc_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Fls_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples_config/Icu_Demo_Cfg/output/generated/soc/j721e/mcu1_0/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/AsrGnrl/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Wdg/include -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/Det/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/MemMap/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/Os/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/Dem/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/Rte/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/EcuM/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/EthIf/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/Fee/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/MemIf/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/AsrGnrl/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/CanIf/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs/WdgIf/inc -I${MCUSW_SDK_PATH}/mcal_drv/mcal/examples/utils -I${TILLVM_PATH}/include
export WDG_LINK_FILES=${MCUSW_SDK_PATH}/binary/wdg_app/obj/j721e_evm/mcu1_0/release/WdgApp.oer5f  ${MCUSW_SDK_PATH}/binary/wdg_app/obj/j721e_evm/mcu1_0/release/Wdg_Cfg.oer5f  ${MCUSW_SDK_PATH}/binary/wdg_app/obj/j721e_evm/mcu1_0/release/Wdg_Lcfg.oer5f  ${MCUSW_SDK_PATH}/binary/wdg_app/obj/j721e_evm/mcu1_0/release/Wdg_PBcfg.oer5f  ${MCUSW_SDK_PATH}/binary/wdg_app/obj/j721e_evm/mcu1_0/release/WdgApp_Startup.oer5f  ${MCUSW_SDK_PATH}/binary/wdg_app/obj/j721e_evm/mcu1_0/release/lld_esm.oer5f  ${MCUSW_SDK_PATH}/binary/wdg_app/obj/j721e_evm/mcu1_0/release/app_utils_wdg.oer5f -Xlinker  ${MCUSW_SDK_PATH}/build/j721e/mcu1_0/linker_r5.lds  -Xlinker --map_file=${MCUSW_SDK_PATH}/binary/wdg_app/bin/j721e_evm/wdg_app_mcu1_0_release.xer5f.map -Xlinker --output_file=${MCUSW_SDK_PATH}/binary/wdg_app/bin/j721e_evm/wdg_app_mcu1_0_release.xer5f -l${MCUSW_SDK_PATH}/binary/mcal/Wdg/lib/j721e/mcu1_0/release/wdg.aer5f -l${MCUSW_SDK_PATH}/binary/mcal/Bsw_Stubs/lib/j721e/r5f/release/bsw_stubs.aer5f -l${MCUSW_SDK_PATH}/binary/mcal/examples/utils/lib/j721e_evm/mcu1_0/release/app_utils.aer5f ${PDK_SDK_PATH}/packages/ti/csl/lib/j721e/r5f/release/ti.csl.aer5f ${PDK_SDK_PATH}/packages/ti/csl/lib/j721e/r5f/release/ti.csl.init.aer5f ${PDK_SDK_PATH}/packages/ti/drv/sciclient/lib/j721e/mcu1_0/release/sciclient_direct.aer5f ${PDK_SDK_PATH}/packages/ti/drv/sciclient/lib/j721e/mcu1_0/release/sciserver_tirtos.aer5f ${PDK_SDK_PATH}/packages/ti/drv/sciclient/lib/j721e/mcu1_0/release/rm_pm_hal.aer5f ${PDK_SDK_PATH}/packages/ti/drv/pm/lib/j721e/r5f/release/pm_lib.aer5f ${PDK_SDK_PATH}/packages/ti/osal/lib/nonos/j721e/r5f/release/ti.osal.aer5f ${PDK_SDK_PATH}/packages/ti/drv/uart/lib/j721e/r5f/release/ti.drv.uart.aer5f ${PDK_SDK_PATH}/packages/ti/board/lib/j721e_evm/r5f/release/ti.board.aer5f ${PDK_SDK_PATH}/packages/ti/drv/i2c/lib/j721e/r5f/release/ti.drv.i2c.aer5f
export TILLVM_PATH=${HOME}/ti/ti-cgt-armllvm_2.1.3.LTS

wdg_compile:
	#make -C ${MCUSW_SDK_PATH}/mcal_drv/mcal/examples/Wdg MCUSW_INSTALL_PATH=${MCUSW_SDK_PATH}
	make -C ${MCUSW_SDK_PATH}/build wdg bsw_stubs app_utils MCUSW_INSTALL_PATH=${MCUSW_SDK_PATH}
	make -C ${MCUSW_SDK_PATH}/mcal_drv/mcal/Wdg -fmakefile MCUSW_INSTALL_PATH=${MCUSW_SDK_PATH}
	make -C ${MCUSW_SDK_PATH}/mcal_drv/mcal/Bsw_Stubs -fmakefile MCUSW_INSTALL_PATH=${MCUSW_SDK_PATH}
	make -C ${MCUSW_SDK_PATH}/mcal_drv/mcal/examples/utils -fmakefile MCUSW_INSTALL_PATH=${MCUSW_SDK_PATH}
	#make ${MCUSW_SDK_PATH}/binary/wdg_app/bin/j721e_evm/wdg_app_mcu1_0_release.xer5f MCUSW_INSTALL_PATH=${MCUSW_SDK_PATH}

	bash ./compile.sh